import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const HelveticaNeue = localFont({
  src: "./fonts/HelveticaNeueMedium.otf",
  variable: "--font-helvetica-neue",
  weight: "100 200 300 400 500 600 700 800 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${HelveticaNeue.variable} antialiased font-helvetica`}
        suppressHydrationWarning
      >
        {children}
      </body>
    </html>
  );
}
